version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: product-postgres
    environment:
      POSTGRES_DB: product_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: basket-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  product-service:
    build:
      context: .
      dockerfile: dockerfiles/product.dockerfile
    container_name: product-service
    ports:
      - "8080:8080"
      - "50050:50050"
    environment:
      - ENVIRONMENT=development
      - PORT=8080
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=product_service
      - DB_SSL_MODE=disable
      - LOG_LEVEL=debug
      - LOG_FORMAT=text
      - LOG_OUTPUT=console
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  basket-service:
    build:
      context: .
      dockerfile: dockerfiles/basket.dockerfile
    container_name: basket-service
    ports:
      - "8081:8081"
    environment:
      - ENVIRONMENT=development
      - PORT=8081
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - PRODUCT_SERVICE_URL=product-service:50050
      - LOG_LEVEL=debug
      - LOG_FORMAT=text
      - LOG_OUTPUT=console
    depends_on:
      redis:
        condition: service_healthy
      product-service:
        condition: service_started
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
