---
# Common role - System configuration tasks

- name: "Update package cache"
  package:
    name: "*"
    state: latest
  when: update_packages | default(true)

- name: "Install essential packages"
  package:
    name:
      - python3
      - python3-pip
      - curl
      - wget
      - unzip
      - git
      - htop
      - vim
      - jq
      - tree
    state: present

- name: "Configure system limits"
  pam_limits:
    domain: "*"
    limit_type: "soft"
    limit_item: "nofile"
    value: "65536"
  when: security_hardening | default(false)

- name: "Configure system limits (hard)"
  pam_limits:
    domain: "*"
    limit_type: "hard"
    limit_item: "nofile"
    value: "65536"
  when: security_hardening | default(false)

- name: "Configure logrotate"
  template:
    src: "logrotate.conf.j2"
    dest: "/etc/logrotate.d/obs-tools-usage"
    mode: '0644'
  notify: "restart rsyslog"

- name: "Configure systemd journal"
  template:
    src: "journald.conf.j2"
    dest: "/etc/systemd/journald.conf"
    mode: '0644'
  notify: "restart systemd-journald"

- name: "Create application directories"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    mode: '0755'
  loop:
    - "/opt/obs-tools-usage"
    - "/var/log/obs-tools-usage"
    - "/etc/obs-tools-usage"

- name: "Configure environment variables"
  template:
    src: "environment.j2"
    dest: "/etc/environment"
    mode: '0644'

- name: "Configure shell profile"
  template:
    src: "bashrc.j2"
    dest: "/home/{{ default_user }}/.bashrc"
    owner: "{{ default_user }}"
    group: "{{ default_group }}"
    mode: '0644'
